### ISSUE TITLE
Install vagrant-libvirt plugin on your laptop

### ISSUE THREAD

**Issue by lioramilbaum** [code-collab-comm/baboon#35]

**Comment by Omeramsc** [comment]
@kittyweg Still having a problem with the installation?
I managed to successfully install it on my machine, try typing in CLI: "yum install libvirt-devel", then install the plugin. 
Tell me if it worked for you.

**Comment by lioramilbaum** [comment]
I was able to install it on my host. I have reinstalled vagrant and that fixed the problem

**Comment by lioramilbaum** [comment]
@Omeramsc please update

**Comment by Omeramsc** [comment]
Not needed anymore.
