### ISSUE TITLE
[documentation] Deploy virtualenvwrapper on host

### ISSUE THREAD

**Issue by lioramilbaum** [code-collab-comm/baboon#38]
Both deploy and add the instructions in the README file

**Comment by IlanZuckerman** [comment]
I'm on it

**Comment by IlanZuckerman** [comment]
@lioramilbaum lets split this issue.
Please Leave the current one as 'Deploy virtualenvwrapper on the vm'
And add additional one for the Documentation.

**Comment by lioramilbaum** [comment]
@IlanZuckerman The task is about deploying it on the host. Not on the guest (VM).
