### ISSUE TITLE
Provisioning Ubuntu vm through CI doesn’t fail when provision script has command which is not unattended (-y)

### ISSUE THREAD

**Issue by IlanZuckerman** [code-collab-comm/baboon#43]
This is a placeholder to track the question / issue i filed to the Travis community:
https://travis-ci.org/IlanZuckerman/baboon/builds/651959361

**Comment by IlanZuckerman** [comment]
**Got an answer from Travis community:**
The following flag is being set by Travis when interacting with debian distros:
DEBIAN_FRONTEND=noninteractive
Basically that means that it will avoid all unnecessary interactions with user. Which is pretty smart you you think about this.

Here is an explanation for this flag:
https://linuxhint.com/debian_frontend_noninteractive/

**Comment by lioramilbaum** [comment]
Got it. We should remember that for next time. Which is not the ideal solution.
