### ISSUE TITLE
Add python lint tests to CI

### ISSUE THREAD

**Issue by Omeramsc** [code-collab-comm/baboon#46]

**Comment by IlanZuckerman** [comment]
I'm on it.
@Omeramsc what code should the linter check? Currently we dont have any Python code at ll on the VM.

**Comment by Omeramsc** [comment]
@IlanZuckerman Good question. I guess you can either test linter on some temporary code or wait for #39 to be merged

**Comment by lioramilbaum** [comment]
Add the flake8 tests before any python code is merged. We know that we are going to have python code in the project. Prepare the CI before the app code is contributed.
